blank_issues_enabled: true
contact_links:
  - name: Getting Help
    url: https://github.com/archriss/react-native-render-html/blob/master/HELP.adoc
    about: A resource which describes all the steps you should go through when you're facing an issue with this library.
